<?php

namespace ContainerDfJGxng;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSwiftmailer_Mailer_Default_Transport_RealService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'swiftmailer.mailer.default.transport.real' shared service.
     *
     * @return \Swift_Transport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['swiftmailer.mailer.default.transport.real'] = \Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SwiftmailerTransportFactory::createTransport(['transport' => 'smtp', 'url' => $container->getEnv('MAILER_URL'), 'username' => null, 'password' => null, 'host' => 'localhost', 'port' => null, 'timeout' => 30, 'source_ip' => null, 'local_domain' => null, 'encryption' => null, 'auth_mode' => null, 'command' => '/usr/sbin/sendmail -bs', 'stream_options' => []], ($container->privates['router.request_context'] ?? $container->getRouter_RequestContextService()), ($container->privates['swiftmailer.mailer.default.transport.eventdispatcher'] ?? ($container->privates['swiftmailer.mailer.default.transport.eventdispatcher'] = new \Swift_Events_SimpleEventDispatcher())));
    }
}
