<?php

namespace ContainerBmqUOrx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qfg0SS3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qfg0SS3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qfg0SS3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.Qfg0SS3.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.Qfg0SS3": it references class "App\\Entity\\Course" but no such service exists.'],
        ], [
            'id' => 'App\\Entity\\Course',
        ]);
    }
}
