<?php

namespace Container3X3A7gO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInscriptionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InscriptionController' shared autowired service.
     *
     * @return \App\Controller\InscriptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\InscriptionController'] = $instance = new \App\Controller\InscriptionController(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\InscriptionController', $container));

        return $instance;
    }
}
