<?php

<<<<<<< HEAD:var/cache/dev/ContainerXXQQ6If/get_ServiceLocator_81dH6S3Service.php
namespace ContainerXXQQ6If;
=======
namespace ContainerFMWyuzO;
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9:var/cache/dev/ContainerFMWyuzO/get_ServiceLocator_UgBB1KxService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
<<<<<<< HEAD:var/cache/dev/ContainerXXQQ6If/get_ServiceLocator_81dH6S3Service.php
class get_ServiceLocator_81dH6S3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.81dH6S3' shared service.
=======
class get_ServiceLocator_UgBB1KxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ugBB1Kx' shared service.
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9:var/cache/dev/ContainerFMWyuzO/get_ServiceLocator_UgBB1KxService.php
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<< HEAD:var/cache/dev/ContainerXXQQ6If/get_ServiceLocator_81dH6S3Service.php
        return $container->privates['.service_locator.81dH6S3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CourseController::indexCSS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController::indexHTML' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController::indexJS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\InscriptionController::index' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\MailController::verificationEmail' => ['privates', '.service_locator.lqzS9y4', 'get_ServiceLocator_LqzS9y4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
=======
        return $container->privates['.service_locator.ugBB1Kx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\InscriptionController::index' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\MailController::verificationEmail' => ['privates', '.service_locator.lqzS9y4', 'get_ServiceLocator_LqzS9y4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::indexDiscover_C_P' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9:var/cache/dev/ContainerFMWyuzO/get_ServiceLocator_UgBB1KxService.php
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CourseController:indexCSS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController:indexHTML' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController:indexJS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\InscriptionController:index' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\MailController:verificationEmail' => ['privates', '.service_locator.lqzS9y4', 'get_ServiceLocator_LqzS9y4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
<<<<<<< HEAD:var/cache/dev/ContainerXXQQ6If/get_ServiceLocator_81dH6S3Service.php
=======
            'App\\Controller\\UserController:indexDiscover_C_P' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9:var/cache/dev/ContainerFMWyuzO/get_ServiceLocator_UgBB1KxService.php
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CourseController::indexCSS' => '?',
            'App\\Controller\\CourseController::indexHTML' => '?',
            'App\\Controller\\CourseController::indexJS' => '?',
            'App\\Controller\\InscriptionController::index' => '?',
            'App\\Controller\\MailController::verificationEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
<<<<<<< HEAD:var/cache/dev/ContainerXXQQ6If/get_ServiceLocator_81dH6S3Service.php
=======
            'App\\Controller\\UserController::indexDiscover_C_P' => '?',
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9:var/cache/dev/ContainerFMWyuzO/get_ServiceLocator_UgBB1KxService.php
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CourseController:indexCSS' => '?',
            'App\\Controller\\CourseController:indexHTML' => '?',
            'App\\Controller\\CourseController:indexJS' => '?',
            'App\\Controller\\InscriptionController:index' => '?',
            'App\\Controller\\MailController:verificationEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
<<<<<<< HEAD:var/cache/dev/ContainerXXQQ6If/get_ServiceLocator_81dH6S3Service.php
=======
            'App\\Controller\\UserController:indexDiscover_C_P' => '?',
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9:var/cache/dev/ContainerFMWyuzO/get_ServiceLocator_UgBB1KxService.php
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
