<?php

<<<<<<< HEAD:var/cache/dev/ContainerX8bC0cJ/getDataCollector_Request_SessionCollectorService.php
namespace ContainerX8bC0cJ;
=======
namespace ContainerFMWyuzO;
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9:var/cache/dev/ContainerFMWyuzO/getDataCollector_Request_SessionCollectorService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataCollector_Request_SessionCollectorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'data_collector.request.session_collector' shared service.
     *
     * @return \Closure
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['data_collector.request.session_collector'] = \Closure::fromCallable([0 => ($container->privates['data_collector.request'] ?? $container->getDataCollector_RequestService()), 1 => 'collectSessionUsage']);
    }
}
