<?php

namespace ContainerQYwTxm7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FoKo8EhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FoKo8Eh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FoKo8Eh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ChangepasswController::index' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\CourseController::indexCSS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController::indexHTML' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController::indexJS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController::indexanglais' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController::indexfrancais' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\InscriptionController::index' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\MailController::verificationEmail' => ['privates', '.service_locator.lqzS9y4', 'get_ServiceLocator_LqzS9y4Service', true],
            'App\\Controller\\ProjectsController::indexAddProject' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::indexEditInfo' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\UserController::indexEditPasswd' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\UserController::indexRemoveMyCourses' => ['privates', '.service_locator.GoXXPot', 'get_ServiceLocator_GoXXPotService', true],
            'App\\Controller\\UserController::indexRemoveMyProjects' => ['privates', '.service_locator.ta6vQ36', 'get_ServiceLocator_Ta6vQ36Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ChangepasswController:index' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\CourseController:indexCSS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController:indexHTML' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController:indexJS' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController:indexanglais' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\CourseController:indexfrancais' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\InscriptionController:index' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\MailController:verificationEmail' => ['privates', '.service_locator.lqzS9y4', 'get_ServiceLocator_LqzS9y4Service', true],
            'App\\Controller\\ProjectsController:indexAddProject' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:indexEditInfo' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\UserController:indexEditPasswd' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\UserController:indexRemoveMyCourses' => ['privates', '.service_locator.GoXXPot', 'get_ServiceLocator_GoXXPotService', true],
            'App\\Controller\\UserController:indexRemoveMyProjects' => ['privates', '.service_locator.ta6vQ36', 'get_ServiceLocator_Ta6vQ36Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ChangepasswController::index' => '?',
            'App\\Controller\\CourseController::indexCSS' => '?',
            'App\\Controller\\CourseController::indexHTML' => '?',
            'App\\Controller\\CourseController::indexJS' => '?',
            'App\\Controller\\CourseController::indexanglais' => '?',
            'App\\Controller\\CourseController::indexfrancais' => '?',
            'App\\Controller\\InscriptionController::index' => '?',
            'App\\Controller\\MailController::verificationEmail' => '?',
            'App\\Controller\\ProjectsController::indexAddProject' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::indexEditInfo' => '?',
            'App\\Controller\\UserController::indexEditPasswd' => '?',
            'App\\Controller\\UserController::indexRemoveMyCourses' => '?',
            'App\\Controller\\UserController::indexRemoveMyProjects' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ChangepasswController:index' => '?',
            'App\\Controller\\CourseController:indexCSS' => '?',
            'App\\Controller\\CourseController:indexHTML' => '?',
            'App\\Controller\\CourseController:indexJS' => '?',
            'App\\Controller\\CourseController:indexanglais' => '?',
            'App\\Controller\\CourseController:indexfrancais' => '?',
            'App\\Controller\\InscriptionController:index' => '?',
            'App\\Controller\\MailController:verificationEmail' => '?',
            'App\\Controller\\ProjectsController:indexAddProject' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:indexEditInfo' => '?',
            'App\\Controller\\UserController:indexEditPasswd' => '?',
            'App\\Controller\\UserController:indexRemoveMyCourses' => '?',
            'App\\Controller\\UserController:indexRemoveMyProjects' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
