<?php

namespace ContainerILQs4O6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ta6vQ36Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ta6vQ36' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ta6vQ36'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.ta6vQ36.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.ta6vQ36": it references class "App\\Entity\\Project" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'id' => 'App\\Entity\\Project',
            'manager' => '?',
        ]);
    }
}
