<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerPxW9jEL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxW9jEL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxW9jEL.legacy');
=======
if (\class_exists(\ContainerJ2QvjwK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2QvjwK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2QvjwK.legacy');
>>>>>>> e76e9cbd518457230509081e80c45e3782872d76

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerPxW9jEL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxW9jEL\App_KernelDevDebugContainer([
    'container.build_hash' => 'PxW9jEL',
    'container.build_id' => 'da69d63a',
    'container.build_time' => 1623506805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxW9jEL');
=======
    \class_alias(\ContainerJ2QvjwK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ2QvjwK\App_KernelDevDebugContainer([
    'container.build_hash' => 'J2QvjwK',
    'container.build_id' => 'f477932c',
    'container.build_time' => 1623601517,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2QvjwK');
>>>>>>> e76e9cbd518457230509081e80c45e3782872d76
