<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerXXQQ6If\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXQQ6If/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXQQ6If.legacy');
=======
if (\class_exists(\ContainerLeUzXLT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLeUzXLT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLeUzXLT.legacy');
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerXXQQ6If\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXQQ6If\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXQQ6If',
    'container.build_id' => '7eeec194',
    'container.build_time' => 1623599643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXQQ6If');
=======
    \class_alias(\ContainerLeUzXLT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLeUzXLT\App_KernelDevDebugContainer([
    'container.build_hash' => 'LeUzXLT',
    'container.build_id' => 'eea397cd',
    'container.build_time' => 1623584304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLeUzXLT');
>>>>>>> f8ba43ef024d074c2dd82002bad2eb2fdb6017d9
